Website/Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

Website/core/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView, name='home'),
    path('getstream', Stream, name='streamdt'),
    path('gettokenstream/<token>', StreamToken, name='streamtk'),
    path('stream/', StreamView, name='streamroom'),
    path('streamtoken/<token>', StreamTokenView, name='stokenview'),
    path('api/', APIEnd, name='api')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Website/core/models.py
from django.db import models
import os


def content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.user.id, instance.questid.id, ext)
    return os.path.join('uploads', filename)


class DocModel(models.Model):
    stoken = models.CharField(max_length=50, unique=False, default='')
    date = models.DateTimeField(auto_now_add=True)
    vid = models.FileField(upload_to='documents/')

    def __str__(self):
        return str(self.date)

Website/core/forms.py
from django import forms
from .models import DocModel

class DocumentForm(forms.ModelForm):
    class Meta:
        model = DocModel
        fields = ('vid', )

Website/core/views.py
from django.views.decorators.clickjacking import xframe_options_exempt
import numpy as np
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse, HttpResponse, StreamingHttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import DocModel
import json
from django.views.decorators import gzip
import cv2
from .forms import DocumentForm
from django.conf import settings
model = settings.MODEL


class VideoCamera(object):
    def __init__(self, url=None):
        self.font = cv2.FONT_HERSHEY_SIMPLEX
        self.status = True
        self.org = (50, 80)
        self.fontScale = 1.4
        self.thickness = 3
        self.SIZE = (150, 150)
        self.THRESH = 0.5
        self.url = 0 if url is None else '.'+url
        self.video = cv2.VideoCapture(self.url)
        self.skipCount = 2
        self.prev = None
        self.fcount = 0

    def __del__(self):
        self.video.release()

    def get_frame(self):
        ret, image = self.video.read()
        if not ret:
            self.status = False
            pass

        if self.fcount % self.skipCount == 0:
            tmp = cv2.resize(image, self.SIZE)
            tmp = tmp / 255.0
            pred = model.predict(np.array([tmp]))
            string = "Violent Activity Detected" if pred[0][0] > self.THRESH else "Peaceful"
            string += f" {str(pred[0][0])}"
            self.prev = string

        else:
            string = self.prev

        color = (255, 255, 255)
        image = cv2.rectangle(image, (20, 20), (600, 100), (0, 200, 100), cv2.FILLED) if string.split(' ')[0] == 'Peaceful' else cv2.rectangle(
            image, (20, 20), (600, 100), (0, 0, 255), cv2.FILLED)
        image = cv2.putText(image, string, self.org, self.font,
                            self.fontScale, color, self.thickness, cv2.LINE_AA)
        ret, jpeg = cv2.imencode('.jpg', image)
        self.fcount += 1
        return jpeg.tobytes()


def gen(camera):
    while camera.status:
        frame = camera.get_frame()
        yield(b'--frame\r\n'b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


@gzip.gzip_page
def Stream(request):
    try:
        entry = DocModel.objects.all().last()
        return StreamingHttpResponse(gen(VideoCamera(entry.vid.url)), content_type="multipart/x-mixed-replace;boundary=frame")
    except StreamingHttpResponse.HttpResponseServerError as e:
        print("aborted")


@gzip.gzip_page
def StreamToken(request, token):
    try:
        entry = DocModel.objects.filter(stoken=token).last()
        return StreamingHttpResponse(gen(VideoCamera(entry.vid.url)), content_type="multipart/x-mixed-replace;boundary=frame")
    except StreamingHttpResponse.HttpResponseServerError as e:
        print("aborted")


def HomeView(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('streamroom')

    else:
        form = DocumentForm()
        return render(request, 'home.html', {'form': form})


# @xframe_options_exempt
def StreamView(request):
    entry = DocModel.objects.all().last()
    if entry is None:
        return JsonResponse({'message': 'No Video Files Yet!'})
    return render(request, 'stream.html')


# API End Point
def StreamTokenView(request, token):
    try:
        entry = DocModel.objects.filter(stoken=token).last()
        if entry is None:
            return JsonResponse({'message': 'Token Not Registered'})

        return render(request, 'streamtoken.html', {'token': token})

    except DocModel.DoesNotExist:
        return JsonResponse({'message': 'Token Not Registered'})


@csrf_exempt
def APIEnd(request):
    if request.method == 'POST':
        try:
            stoken = request.POST['stoken']
            vidFile = request.FILES['vid']
            DocModel(stoken=stoken, vid=vidFile).save()
            baseurl = request.build_absolute_uri(reverse('home'))
            return JsonResponse({'status': 'ok', 'message': f'Files Received from sender {stoken}', 'vidurl': baseurl+'streamtoken/'+stoken})
        except:
            return HttpResponse(status=400)

    return JsonResponse({'status': 'Wait bro'})

Website/templates/home.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Voilence XP</title>
    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">
    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="assets/css/scroll.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">
</head>

<body>
    <section id="hero">
        <div class="hero-container">
            <div class="hero-logo" data-aos="zoom-in"><img src="assets/img/favicon.png" alt="" id="main_img"></div>
            <h1 data-aos="zoom-in"><span id="glow">Vision</span></h1>
            <h2 data-aos="fade-up">Problem Domain: Safety and Surveillance</h2>
            <a data-aos="fade-up" data-aos-delay="200" href="#about" class="btn-get-started scrollto">Get Started</a>
        </div>
    </section><!-- End Hero -->

    <!-- ======= Header ======= -->
    <header id="header" class="d-flex align-items-center">
        <div class="container d-flex align-items-center justify-content-between">

            <div class="logo">
                <span id="nav-title">Vision</span>
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Services</a></li>
                    <li><a class="nav-link scrollto" href="#team">Team</a></li>
            </nav>

        </div>
    </header><!-- End Header -->

    <main id="main">

        <!-- ======= About Us Section ======= -->
        <section id="about" class="about">
            <div class="container">
                <div class="section-title" data-aos="fade-up">
                    <h3>Solving the issue from a different, wider perspective. </h3>
                </div>

                <div class="row">
                    <div class="col-lg-6" data-aos="fade-right">
                        <div class="image" style="padding-top: 0;">
                            <img src="assets/img/about.png" class="img-fluid" alt="">
                        </div>
                    </div>
                    <div class="col-lg-6 pt-3" data-aos="fade-left">
                        <div class="content pt-4 pt-lg-0 pl-0 pl-lg-3 ">
                            <h4>Surveillance is an integral part of security and control.</h4>
                            <p class="font-italic">
                                Requires extended periods of examining multiple footages for evidence. This manual task
                                provides
                                evidence in court but is rarely used to detect and prevent crime in real-time.
                                We bring a solution to ensure a step towards safety of women and reduce the crime
                                statistics.

                            </p>
                            <p>
                                We convert an evidence collecting tool to a crime prevention and detection tool.
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </section><!-- End About Us Section -->
        <section id="upload" class="upload">
            <div id="particles-js"></div>
            <div class="section-title" data-aos="fade-up">
                <h2>Test our Project Live!</h2>
                <p>Use the button given below to test out our project.</p>
            </div>
            <div class="d-flex align-items-center justify-content-center" data-aos="fade-up">
                <form method="post" enctype="multipart/form-data" id="vid_form">
                    {% csrf_token %}
                    <input type="file" accept=".mp4" name="vid" required="" id="id_vid" hidden>
                    <label for="id_vid" class=" fBtn cta-btn align-middle" style="cursor: pointer;">Choose Video
                        File</label>
                    <button class="btn btn-secondary" hidden>Submit</button>
                </form>
            </div>

        </section>
        </section>
        <!-- ======= Services Section ======= -->
        <section id="services" class="services">
            <div class="container">
                <div class="section-title" data-aos="fade-up">
                    <h2>Tech Stack</h2>
                    <p>This project encompasses various technologies within itself.</p>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-6 icon-box mt-2" data-aos="fade-up">
                        <i class="bx bx-receipt"></i>
                        <h4>Tensorflow</h4>
                        <p>Prediction and analysis</p>
                    </div>
                    <div class="col-12 col-lg-6 icon-box mt-2" data-aos="fade-up" data-aos-delay="100">
                        <i class="bx bx-cube-alt"></i>
                        <h4>OpenCV</h4>
                        <p>Video frame capturing and pre-processing</p>
                    </div>
                    <div class="col-12 col-lg-6 icon-box mt-2" data-aos="fade-up" data-aos-delay="200">
                        <i class="bx bx-images"></i>
                        <h4>Django</h4>
                        <p>Web Platform, API End point and Job Scheduler for Tensorflow</p>
                    </div>
                
                </div>

            </div>
        </section><!-- End Services Section -->

        <section id="team" class="team">
            <div class="container">

                <div class="section-title" data-aos="fade-up">
                    <h2>Team</h2>
                    <p>Working for a better tomorrow</p>
                </div>

                <div class="row">
                    <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                        <div class="member d-flex flex-column align-items-center" data-aos="zoom-in">
                            <div class="member-img">
                                <img src="assets/img/team/JAGA_PIC.png" class="img-fluid" alt="">
                            </div>
                            <div class="member-info">
                                <h4>JAGADEESH M</h4>
                                <span>AI & DS 3RD YEAR</span>
                            </div>

                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                        <div class="member d-flex flex-column align-items-center" data-aos="zoom-in"
                            data-aos-delay="100">
                            <div class="member-img">
                                <img src="assets/img/team/ATHIQ_PIC.png" class="img-fluid" alt="">

                            </div>
                            <div class="member-info">
                                <h4>ATHIQUR RAASITH M S</h4>
                                <span>AI & DS 3RD YEAR</span>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                        <div class="member d-flex flex-column align-items-center" data-aos="zoom-in"
                            data-aos-delay="200">
                            <div class="member-img">
                                <img src="assets/img/team/KANISH_PIC.png" class="img-fluid" alt="">
                            </div>
                            <div class="member-info">
                                <h4>KANISHKARAN M</h4>
                                <span>AI & DS 3RD year</span>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- End Team Section -->

    </main><!-- End #main -->

    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <a href="#header" class="scrollto footer-logo"><img src="assets/img/favicon.png" alt=""></a>
                        <h3>Team ZODIACS</h3>
                    </div>
                </div>
            </div>
        </div>

        <div class="container footer-bottom clearfix">
            <div class="copyright">
                &copy; Copyright <strong><span>Team ZODIACS</span></strong>. All Rights Reserved
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="assets/vendor/aos/aos.js"></script>
    <script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="assets/particles/particles.min.js"></script>
    <script src="assets/particles/app.js"></script>
    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>

    <script type="text/javascript">
        document.getElementById('vid_form').onchange = function () {
            document.getElementById('vid_form').submit();
        };
    </script>
</body>

</html>

Website/templates/stream.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
    <link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/styles.css'%}">
    <link rel="stylesheet" href="{%static 'css/streamtoken.css'%}">
</head>

<body>
    <div class="container-fluid">
        <header class="mb-2">
            <div class="row">
                <span class="col-3">
                    <a href="{%url 'home'%}" id="backLink"> &lAarr; Back to Page</a>
                </span>
                <span class="col-6">
                    <h1 class="text-center" style="margin: 0;">Result</h1>
                </span>
                <span class="col-3"></span>
            </div>
        </header>
        <hr class="my-1 mb-3">
        <div class="d-flex justify-content-center align-items-center">
            <img src="{%url 'streamdt'%}" id='vidHolder' style="width: 85%;">
        </div>
    </div>
    <script src="{%static 'bootstrap/js/bootstrap.bundle.js'%}"></script>
</body>

</html>

Website/templates/streamtoken.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
    <link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'boxicon/css/boxicons.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/streamtoken.css'%}">
    <link rel="stylesheet" href="{%static 'css/styles.css'%}">
    <link rel="stylesheet" href="{%static 'css/fa.css'%}">
</head>

<body>
    <main>
        <header>
            <nav id="stickynav">
                <button id="minBtn" class="ctrlBtn"><i class='bx bx-minus'></i></button>
                <button id="closeBtn" class="ctrlBtn"><i class="fas fa-times"></i></button>
            </nav>
        </header>
        <div class="container-fluid">
            <h1 class="text-center mb-2" style="margin: 0;">Result</h1>
            <hr class="my-1 mb-3">
            <div class="d-flex justify-content-center align-items-center">
                <img src="{%url 'streamtk' token%}" id='vidHolder'>
            </div>
        </div>
    </main>
    <script src="{%static 'bootstrap/js/bootstrap.bundle.js'%}"></script>

    <script src="{%static 'js/electron.js'%}"></script>
</body>

</html>

Website/templates/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="http://localhost:8000/api/" method="POST">
        <input name="stoken" type="text">
        <input type="submit">
    </form>
</body>

</html>